# Generated by Django 4.0.4 on 2022-06-24 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archetype',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Archetype',
                'verbose_name_plural': 'Archetypes',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('class_type', models.CharField(choices=[('Monster', 'Monster'), ('Trampa', 'Trampa')], max_length=20)),
                ('archetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ygo.archetype', verbose_name='archetype')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
            },
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('main_deck', models.PositiveSmallIntegerField()),
                ('extra_deck', models.PositiveSmallIntegerField()),
                ('side_deck', models.PositiveSmallIntegerField()),
                ('archetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to='ygo.archetype', verbose_name='archetype')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.player', verbose_name='player')),
            ],
        ),
        migrations.CreateModel(
            name='DeckCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MD', models.BooleanField()),
                ('SD', models.BooleanField()),
                ('ED', models.BooleanField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ygo.card', verbose_name='card')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='ygo.deck', verbose_name='deck')),
            ],
            options={
                'verbose_name': 'DeckCards',
                'verbose_name_plural': 'DeckCardss',
            },
        ),
    ]
